### ISSUE TITLE
Compass not finding caves biomes

### ISSUE THREAD

**Issue by kylian-plard** [MattCzyr/NaturesCompass#128]
Hello there
I found that the compass has caves in the list, like diorite or dripstone caves, but can't find them when trying to locate them :

![2022-02-20_14 13 57](https://user-images.githubusercontent.com/11462348/154844429-a5a859b3-9bd4-4518-a51b-1e3428aa19d0.png)

![2022-02-20_14 14 06](https://user-images.githubusercontent.com/11462348/154844442-449848a7-379a-4be8-9ef8-353babcd9a5d.png)

![2022-02-20_14 14 20](https://user-images.githubusercontent.com/11462348/154844464-8bd5be71-0772-40bf-a3c7-d728d50a1b1f.png)

![2022-02-20_14 14 17](https://user-images.githubusercontent.com/11462348/154844478-13c00ae5-004a-4017-a438-a1bdbfb4e17c.png)

Thanks in advance :)

**Comment by MattCzyr** [comment]
This has been fixed in 1.9.5-forge and 2.0.3-fabric. The compass will now search for biomes relative to the player's Y coordinate, so if you're looking for a cave biome it'll help to go to the height at which they generate before searching.

**Comment by Roadhog360** [comment]
@MattCzyr 
> This has been fixed in 1.9.5-forge and 2.0.3-fabric. The compass will now search for biomes relative to the player's Y coordinate, so if you're looking for a cave biome it'll help to go to the height at which they generate before searching.



This issue still occurs in the 1.16.5 Forge version of the mod. Is there any chance that fix could be backported if 1.16.5 is still supported?
