### ISSUE TITLE
Crash when searching in singleplayer

### ISSUE THREAD

**Issue by sine707** [MattCzyr/NaturesCompass#37]
I installed the mod and upon the first search for a roofed forest biome the game crashes.
When I re-enter the game the compass states that it is searching but when I try to search again it crashes again.
[crash-2019-11-28_02.10.04-server.txt](https://github.com/MattCzyr/NaturesCompass/files/3899356/crash-2019-11-28_02.10.04-server.txt)

**Comment by MattCzyr** [comment]
Does the game crash immediately after you try to search for the biome, or does it hang for a while before it crashes?

Also, please try replicating this issue under the *exact same* circumstances with version 1.5.1 and let me know if it persists. I.e, find circumstances in which the game crashes in 1.6.0, then switch to 1.5.1 and see if it still crashes. I'm trying to figure out if this is a performance configuration issue or if this is unique to 1.6.0.

**Comment by sine707** [comment]
When I clicked "Start Search" it became unresponsive, I couldn't move or look around and the frame freezed for about 5 seconds. Then it crashed to desktop.

I had the mod disabled yesterday, re-enabled it today and the search for "Roofed Forest" was successful now. However, a search for the "Cold Taiga Hills" had a "Waiting for server" message come up in One Probe, then the same crash happened.

Here's the crash log (1.6.0), in case this new scenario is of use to you:
https://pastebin.com/0xGsuWTq

I tried the exact same with several biomes under 1.5.1 and everything went fine, no crashes.

**Comment by MattCzyr** [comment]
The underlying issue has been brought to my attention and I'm currently working on a fix. Thanks for following up.

**Comment by MattCzyr** [comment]
This issue should be fixed as of version 1.6.1 (out now), but please try it out and confirm.

**Comment by sine707** [comment]
I installed 1.6.1 and sadly the problem persists, I tried with using the existing compass and also trash-canned the "old" and crafted a new one if that makes any difference. Same results.

1.6.1 crash log:
https://pastebin.com/RWB1sUKq

**Comment by MattCzyr** [comment]
Just released version 1.6.2. There's a new config field that specifies how many new chunks can be generated per search, and max distance is calculated a bit differently. Delete your config before updating and let me know if this fixes the issue.

**Comment by sine707** [comment]
I deleted the config file and it seems to have fixed the issue! :)
Thank you so much for your hard work!
